<a href="https://colab.research.google.com/github/RojaCM/NLP/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import torch

In [3]:
a=np.array(1)

In [4]:
b=torch.tensor(1)

In [6]:
type(a)

numpy.ndarray

In [7]:
type(b)

torch.Tensor

In [8]:
a = np.array(2)
b = np.array(1)
print(a,b)

2 1


In [9]:
a+b

3

In [10]:
a*b

2

In [11]:
a/b

2.0

In [12]:
a//b

2

In [13]:
a-b

1

In [14]:
c=torch.tensor(1)

In [15]:
d=torch.tensor(3)

In [17]:
c+d

tensor(4)

In [18]:
c-d

tensor(-2)

In [19]:
c/d

tensor(0.3333)

In [20]:
c*d

tensor(3)

In [21]:
a=np.zeros((3,3))

In [22]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
e=torch.zeros((3,3))

In [34]:
e

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [35]:
f=torch.zeros((3,3))

In [36]:
e.shape

torch.Size([3, 3])

In [37]:
f.shape

torch.Size([3, 3])

In [39]:
e*f

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [53]:
np.random.seed(42)
a1=np.random.randint(1,100,[3,3])

In [54]:
a1

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75]])

In [55]:
b=np.random.randn(3,3)

In [56]:
b

array([[-2.01096289, -0.49280342,  0.39257975],
       [-0.92918467,  0.07983181, -0.1595165 ],
       [ 0.02222183, -0.42779291, -0.53181741]])

In [57]:
torch.manual_seed(32)
a2=torch.randn(3,3)

In [58]:
a2

tensor([[ 0.8651,  0.0284,  0.5256],
        [-0.3633, -0.4169, -1.2650],
        [ 1.2367,  0.1980, -1.5811]])

In [61]:
np.random.seed(42)
aa=np.random.randn(3,3)
ab=np.random.randn(3,3)

In [62]:
aa+ab

array([[ 1.0392742 , -0.60168199,  0.18195878],
       [ 1.76499213, -2.14743362, -1.95905479],
       [ 1.01692529, -0.24539639, -0.15522705]])

In [63]:
aa-ab

array([[-0.04584589,  0.32515339,  1.11341829],
       [ 1.28106758,  1.67912687,  1.49078088],
       [ 2.14150034,  1.78026585, -0.78372172]])

In [64]:
np.add(aa,ab)

array([[ 1.0392742 , -0.60168199,  0.18195878],
       [ 1.76499213, -2.14743362, -1.95905479],
       [ 1.01692529, -0.24539639, -0.15522705]])

In [65]:
aa*ab

array([[ 0.26949725,  0.06407412, -0.30164782],
       [ 0.36851576,  0.44800103,  0.40386701],
       [-0.88797167, -0.77728178, -0.14753107]])

In [66]:
np.dot(aa,ab)

array([[-0.12814468, -0.62164688,  0.21069439],
       [ 0.90133115, -0.02065676, -0.3790019 ],
       [ 1.30648762, -1.7246546 , -2.20677932]])

In [67]:
aa/ab

array([[ 0.9155008 ,  0.29835784, -1.39069607],
       [ 6.29449313,  0.12238321,  0.13573803],
       [-2.80855031, -0.75771243, -1.49396459]])

In [68]:
np.divide(aa,ab)

array([[ 0.9155008 ,  0.29835784, -1.39069607],
       [ 6.29449313,  0.12238321,  0.13573803],
       [-2.80855031, -0.75771243, -1.49396459]])

In [69]:
aa

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [70]:
np.transpose(aa)

array([[ 0.49671415,  1.52302986,  1.57921282],
       [-0.1382643 , -0.23415337,  0.76743473],
       [ 0.64768854, -0.23413696, -0.46947439]])

In [71]:
torch.manual_seed(42)
a3=torch.randn(3,3)
a4=torch.randn(3,3)

In [72]:
torch.add(a3,a4)

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])

In [73]:
torch.divide(a3,a4)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [74]:
torch.div(a3,a4)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [75]:
torch.mm(a3,a4)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [76]:
a5=torch.randn(2,2)

In [77]:
a5

tensor([[-0.7658, -0.7506],
        [ 1.3525,  0.6863]])

In [78]:
a6=torch.tensor([[1,2],[3,4]])

In [79]:
a6

tensor([[1, 2],
        [3, 4]])

In [82]:
torch.cat((a5,a6))

tensor([[-0.7658, -0.7506],
        [ 1.3525,  0.6863],
        [ 1.0000,  2.0000],
        [ 3.0000,  4.0000]])

In [83]:
torch.cat((a5,a6),dim=1)

tensor([[-0.7658, -0.7506,  1.0000,  2.0000],
        [ 1.3525,  0.6863,  3.0000,  4.0000]])

In [84]:
torch.manual_seed(42)
a7=torch.randn(2,4)

In [85]:
a7.shape

torch.Size([2, 4])

In [86]:
a7.reshape(8,-1)

tensor([[ 0.3367],
        [ 0.1288],
        [ 0.2345],
        [ 0.2303],
        [-1.1229],
        [-0.1863],
        [ 2.2082],
        [-0.6380]])

In [87]:
a7

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])

In [88]:
a7.reshape(1,-1)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])

In [89]:
a8=np.random.randn(10)

In [90]:
a8

array([-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ,  0.0675282 ,
       -1.42474819, -0.54438272,  0.11092259, -1.15099358,  0.37569802])

In [91]:
a9=torch.from_numpy(a8)

In [92]:
a9

tensor([-0.9080, -1.4123,  1.4656, -0.2258,  0.0675, -1.4247, -0.5444,  0.1109,
        -1.1510,  0.3757], dtype=torch.float64)