<a href="https://colab.research.google.com/github/RojaCM/NLP/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Gather data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow.datasets as tfds

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow_datasets as tfds

In [9]:
dataset=tfds.load('amazon_us_reviews/Mobile_Electronics_v1_00',split='train',shuffle_files=True)

In [10]:
# Create empty lists for the desired columns
review_body_list = []
star_rating_list = []

# Iterate through the dataset and extract values
for example in dataset:
    review_body = example['data']['review_body'].numpy().decode('utf-8')
    star_rating = example['data']['star_rating'].numpy()

    review_body_list.append(review_body)
    star_rating_list.append(star_rating)

# Create a dataframe from the lists
df = pd.DataFrame({'review_body': review_body_list, 'star_rating': star_rating_list})

#Explore the dataset

In [11]:
df

review_body  star_rating
0                                           Does not work            1
1       This is a great wiring kit i used it to set up...            4
2       It works great so much faster than USB charger...            5
3       This product was purchased to hold a monitor o...            5
4       it works but it has really bad sound quality. ...            3
...                                                   ...          ...
104970  It's a wonderful invention. You don't need to ...            4
104971  This is not good item,I can even maket work,th...            1
104972  The cover and skin were both exactly like the ...            5
104973  I ordered 2 of these cords for both mine and m...            1
104974  Item works better than I had hoped for. Very c...            5

[104975 rows x 2 columns]

In [12]:
df.shape

(104975, 2)

In [13]:
df['star_rating'].nunique()

5

In [14]:
df['star_rating'].value_counts()

5    52255
4    18088
1    17587
3     9734
2     7311
Name: star_rating, dtype: int64

In [15]:
#take a 50% sample of dataset

In [16]:
data=df.sample(frac=0.3,random_state=42).reset_index(drop=True)

In [17]:
data.head()

review_body  star_rating
0  The motor spins and is not stationary. That se...            3
1                                               Fake            1
2  Even though there are finally some silicone ca...            5
3  Absolutely Wonderful:  This product is everyth...            5
4  Love this Bluetooth speaker...easy setup, wond...            5

In [18]:
data.shape

(31492, 2)

In [19]:
data['sentiment']=data['star_rating'].apply(lambda x:'positive' if x>=3 else 'negative')

In [20]:
data.head()

review_body  star_rating sentiment
0  The motor spins and is not stationary. That se...            3  positive
1                                               Fake            1  negative
2  Even though there are finally some silicone ca...            5  positive
3  Absolutely Wonderful:  This product is everyth...            5  positive
4  Love this Bluetooth speaker...easy setup, wond...            5  positive

In [21]:
data['sentiment'].value_counts()

positive    24067
negative     7425
Name: sentiment, dtype: int64

In [22]:
data['sentiment']=data['sentiment'].map({'positive':1,'negative':0})

In [23]:
data

review_body  star_rating  \
0      The motor spins and is not stationary. That se...            3   
1                                                   Fake            1   
2      Even though there are finally some silicone ca...            5   
3      Absolutely Wonderful:  This product is everyth...            5   
4      Love this Bluetooth speaker...easy setup, wond...            5   
...                                                  ...          ...   
31487  I bought this speaker for my wife who loves mu...            5   
31488  I bought this because I wanted to be able to b...            5   
31489  Great product and really simple to install.  D...            5   
31490  This product works as advertised.  It protects...            4   
31491  Received the package promptly, well packaged. ...            4   

       sentiment  
0              1  
1              0  
2              1  
3              1  
4              1  
...          ...  
31487          1  
31488          1  
31489          1  
31490          1  
31491          1  

[31492 rows x 3 columns]

In [24]:
data['sentiment'].value_counts()

1    24067
0     7425
Name: sentiment, dtype: int64

In [25]:
data1=data.copy()

In [26]:
data.rename(columns={'review_body':'review'},inplace=True)

In [27]:
data

review  star_rating  \
0      The motor spins and is not stationary. That se...            3   
1                                                   Fake            1   
2      Even though there are finally some silicone ca...            5   
3      Absolutely Wonderful:  This product is everyth...            5   
4      Love this Bluetooth speaker...easy setup, wond...            5   
...                                                  ...          ...   
31487  I bought this speaker for my wife who loves mu...            5   
31488  I bought this because I wanted to be able to b...            5   
31489  Great product and really simple to install.  D...            5   
31490  This product works as advertised.  It protects...            4   
31491  Received the package promptly, well packaged. ...            4   

       sentiment  
0              1  
1              0  
2              1  
3              1  
4              1  
...          ...  
31487          1  
31488          1  
31489          1  
31490          1  
31491          1  

[31492 rows x 3 columns]

In [28]:
data['review']=data['review'].apply(str.lower)

In [29]:
data

review  star_rating  \
0      the motor spins and is not stationary. that se...            3   
1                                                   fake            1   
2      even though there are finally some silicone ca...            5   
3      absolutely wonderful:  this product is everyth...            5   
4      love this bluetooth speaker...easy setup, wond...            5   
...                                                  ...          ...   
31487  i bought this speaker for my wife who loves mu...            5   
31488  i bought this because i wanted to be able to b...            5   
31489  great product and really simple to install.  d...            5   
31490  this product works as advertised.  it protects...            4   
31491  received the package promptly, well packaged. ...            4   

       sentiment  
0              1  
1              0  
2              1  
3              1  
4              1  
...          ...  
31487          1  
31488          1  
31489          1  
31490          1  
31491          1  

[31492 rows x 3 columns]

In [30]:
#balancing the datasets

positive=data[data['sentiment']==1].sample(n=7425,random_state=42)

In [31]:
negative=data[data['sentiment']==0]

In [32]:
train_data=pd.concat([positive,negative]).sample(frac=1).reset_index(drop=True)

In [33]:
train_data

review  star_rating  \
0      wraps around perimeter of screen so texting ca...            2   
1      basically you get what you pay for with this p...            1   
2      shipped quickly, arrived as expected, quality ...            5   
3               i did not like it, the leather came off.            1   
4      i was a little nervous about the bag initially...            5   
...                                                  ...          ...   
14845  i am buying this product for my 3 year old.  l...            5   
14846  i bought for a project but when it came it wou...            3   
14847  beautiful meaningful art.the figure of a woman...            5   
14848  comes without instructions. really! does not f...            1   
14849  product met expectations,love the color. very ...            1   

       sentiment  
0              0  
1              0  
2              1  
3              0  
4              1  
...          ...  
14845          1  
14846          1  
14847          1  
14848          0  
14849          0  

[14850 rows x 3 columns]

In [34]:
#sample reviews and labels
reviews=train_data['review'].tolist()
labels=train_data['sentiment'].tolist()

In [35]:
reviews[10:15]

["this seems to be a well made product.  the only issue i have is with the volume buttons but seeing that i rarely use them it isn't a big deal.",
 'i was a little worried from seeing other reviews of this product (in different colors) that it wouldn\'t fit properly.  several reviewers said it was too tight on their kindle.  perhaps they are trying to fit it around their kindle and a kindle case?  i read on my kindle without any other case, and this is exactly what i was looking for -- something to protect the screen from getting scratched or dusty inside my purse.  my \\\\"naked\\\\" kindle fit in the case perfectly.  the only possible downside to this case is that the charging cord would be a bit bulky in the back pocket, but i don\'t normally tote my charging cord around with me, since the battery lasts a long time -- so this isn\'t a downside for me.  also, this is a very very nice pop of color orange.  at least on my computer screen, the orange looks a bit faded, but in real life,

In [36]:
labels[10:15]

[1, 1, 1, 0, 1]

In [37]:
#split the dataset into train,test and validation

from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test=train_test_split(reviews,labels,test_size=0.2,random_state=42)

In [39]:
len(x_train)

11880

In [40]:
len(x_test)

2970

In [41]:
#load the tokenizer
!pip install transformers
from transformers import DistilBertTokenizerFast
model_name='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer= DistilBertTokenizerFast.from_pretrained(model_name)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 27.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 27.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 93.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 66.8 MB/s eta 0:00:00


In [42]:
#sample tokenization
print('sentence',x_train[0])
tokenizer(x_train[0],truncation=True,padding=True,max_length=256,return_tensors="tf")

sentence does not fit ipod touch 4 gen. was not clear that it would not fit this ipod.<br />did give permission to return them, that is  good


{'input_ids': <tf.Tensor: shape=(1, 35), dtype=int32, numpy=
array([[  101,  2515,  2025,  4906, 26322,  3543,  1018,  8991,  1012,
         2001,  2025,  3154,  2008,  2009,  2052,  2025,  4906,  2023,
        26322,  1012,  1026,  7987,  1013,  1028,  2106,  2507,  6656,
         2000,  2709,  2068,  1010,  2008,  2003,  2204,   102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 35), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

#PERFORM TOKENIZATION

In [43]:
MAX_LENGTH=256
train_encodings=tokenizer(x_train,truncation=True,padding=True,max_length=256,return_tensors="tf")

In [44]:
test_encodings=tokenizer(x_test,truncation=True,padding=True,max_length=256,return_tensors="tf")

In [47]:
import tensorflow as tf

In [48]:
#convert the tokenizer to TF object
train_dataset=tf.data.Dataset.from_tensor_slices((dict(train_encodings),y_train))

In [49]:
test_dataset=tf.data.Dataset.from_tensor_slices((dict(test_encodings),y_test))

In [50]:
import tensorflow as tf

In [51]:
from transformers import TFDistilBertForSequenceClassification

In [52]:
model=TFDistilBertForSequenceClassification.from_pretrained(pretrained_model_name_or_path=model_name,num_labels=2)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [53]:
optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5)

In [54]:
loss_func=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [55]:
model.compile(optimizer=optimizer,loss=loss_func,metrics=['accuracy'])

In [56]:
model.summary()

Model: "tf_distil_bert_for_sequence_classification"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 distilbert (TFDistilBertMai  multiple                 66362880  
 nLayer)                                                         
                                                                 
 pre_classifier (Dense)      multiple                  590592    
                                                                 
 classifier (Dense)          multiple                  1538      
                                                                 
 dropout_19 (Dropout)        multiple                  0         
                                                                 
Total params: 66,955,010
Trainable params: 66,955,010
Non-trainable params: 0
_________________________________________________________________


In [57]:
batch_size=12
epochs=2

In [58]:
model.fit(train_dataset.shuffle(len(x_train)).batch(batch_size),epochs=epochs,batch_size=batch_size,validation_data=test_dataset.shuffle(len(x_test)).batch(batch_size))

Epoch 1/2
990/990 [==============================] - 481s 422ms/step - loss: 0.2746 - accuracy: 0.8877 - val_loss: 0.2232 - val_accuracy: 0.9158
Epoch 2/2
990/990 [==============================] - 353s 357ms/step - loss: 0.1612 - accuracy: 0.9412 - val_loss: 0.2541 - val_accuracy: 0.9077


In [59]:
model.save_pretrained("/tmp/sentiment_model")

In [60]:
unseen_data=data.sample(frac=0.5,random_state=42)
unseen_review=unseen_data['review'].to_list()

unseen_encodings=tokenizer(unseen_review,padding=True,truncation=True,max_length=256,return_tensors="tf")

In [61]:
y_unseen=unseen_data['sentiment'].tolist()
unseen_encodings=tf.data.Dataset.from_tensor_slices((dict(unseen_encodings),y_unseen))

In [63]:
model.evaluate(unseen_encodings.shuffle(len(unseen_review)).batch(batch_size),return_dict=True,batch_size=batch_size)

1313/1313 [==============================] - 157s 120ms/step - loss: 0.2148 - accuracy: 0.9252


{'loss': 0.21481946110725403, 'accuracy': 0.925187349319458}

In [64]:
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 80.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.7/65.7 kB 7.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.0/289.0 kB 34.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 kB 10.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 kB 18.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 17.6 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of mdit-py-plugins to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 6.7 MB/s eta 0:00:00
  

In [65]:
import gradio as gr

In [66]:
def predict(sentence):
  loaded_model=TFDistilBertForSequenceClassification.from_pretrained("tmp/sentiment_model")
  predict_input=tokenizer.encode(sentence,truncation=True,padding=True,return_tensor='tf')
  tf_output=loaded_model.predict(predict_input)[0]
  tf_prediction=tf.nn.softmax(tf_output,axis=1).numpy[0]
  return ['negative','positive'][np.argmax(tf_prediction)]

In [68]:
demo=gr.Interface(fn=predict,inputs='text',outputs='text',live=True)
demo.launch()

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Note: opening Chrome Inspector may crash demo inside Colab notebooks.

To create a public link, set `share=True` in `launch()`.


<IPython.core.display.Javascript object>