<a href="https://colab.research.google.com/github/RojaCM/NLP/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Gather data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow.datasets as tfds

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow_datasets as tfds

In [3]:
dataset=tfds.load('amazon_us_reviews/Mobile_Electronics_v1_00',split='train',shuffle_files=True)

In [23]:
# Create empty lists for the desired columns
review_body_list = []
star_rating_list = []

# Iterate through the dataset and extract values
for example in dataset:
    review_body = example['data']['review_body'].numpy().decode('utf-8')
    star_rating = example['data']['star_rating'].numpy()

    review_body_list.append(review_body)
    star_rating_list.append(star_rating)

# Create a dataframe from the lists
df_1 = pd.DataFrame({'review_body': review_body_list, 'star_rating': star_rating_list})

#Explore the dataset

In [24]:
df

review_body  star_rating
0                                           Does not work            1
1       This is a great wiring kit i used it to set up...            4
2       It works great so much faster than USB charger...            5
3       This product was purchased to hold a monitor o...            5
4       it works but it has really bad sound quality. ...            3
...                                                   ...          ...
104970  It's a wonderful invention. You don't need to ...            4
104971  This is not good item,I can even maket work,th...            1
104972  The cover and skin were both exactly like the ...            5
104973  I ordered 2 of these cords for both mine and m...            1
104974  Item works better than I had hoped for. Very c...            5

[104975 rows x 2 columns]

In [25]:
df.shape

(104975, 2)

In [26]:
df['star_rating'].nunique()

5

In [27]:
df['star_rating'].value_counts()

5    52255
4    18088
1    17587
3     9734
2     7311
Name: star_rating, dtype: int64

In [28]:
#take a 50% sample of dataset

In [29]:
data=df.sample(frac=0.3,random_state=42).reset_index(drop=True)

In [30]:
data.head()

review_body  star_rating
0  The motor spins and is not stationary. That se...            3
1                                               Fake            1
2  Even though there are finally some silicone ca...            5
3  Absolutely Wonderful:  This product is everyth...            5
4  Love this Bluetooth speaker...easy setup, wond...            5

In [31]:
data.shape

(31492, 2)

In [32]:
data['sentiment']=data['star_rating'].apply(lambda x:'positive' if x>=3 else 'negative')

In [33]:
data.head()

review_body  star_rating sentiment
0  The motor spins and is not stationary. That se...            3  positive
1                                               Fake            1  negative
2  Even though there are finally some silicone ca...            5  positive
3  Absolutely Wonderful:  This product is everyth...            5  positive
4  Love this Bluetooth speaker...easy setup, wond...            5  positive

In [34]:
data['sentiment'].value_counts()

positive    24067
negative     7425
Name: sentiment, dtype: int64

In [35]:
data['sentiment']=data['sentiment'].map({'positive':1,'negative':0})

In [36]:
data

review_body  star_rating  \
0      The motor spins and is not stationary. That se...            3   
1                                                   Fake            1   
2      Even though there are finally some silicone ca...            5   
3      Absolutely Wonderful:  This product is everyth...            5   
4      Love this Bluetooth speaker...easy setup, wond...            5   
...                                                  ...          ...   
31487  I bought this speaker for my wife who loves mu...            5   
31488  I bought this because I wanted to be able to b...            5   
31489  Great product and really simple to install.  D...            5   
31490  This product works as advertised.  It protects...            4   
31491  Received the package promptly, well packaged. ...            4   

       sentiment  
0              1  
1              0  
2              1  
3              1  
4              1  
...          ...  
31487          1  
31488          1  
31489          1  
31490          1  
31491          1  

[31492 rows x 3 columns]

In [37]:
data['sentiment'].value_counts()

1    24067
0     7425
Name: sentiment, dtype: int64

In [38]:
data1=data.copy()

In [41]:
data.rename(columns={'review_body':'review'},inplace=True)

In [42]:
data

review  star_rating  \
0      The motor spins and is not stationary. That se...            3   
1                                                   Fake            1   
2      Even though there are finally some silicone ca...            5   
3      Absolutely Wonderful:  This product is everyth...            5   
4      Love this Bluetooth speaker...easy setup, wond...            5   
...                                                  ...          ...   
31487  I bought this speaker for my wife who loves mu...            5   
31488  I bought this because I wanted to be able to b...            5   
31489  Great product and really simple to install.  D...            5   
31490  This product works as advertised.  It protects...            4   
31491  Received the package promptly, well packaged. ...            4   

       sentiment  
0              1  
1              0  
2              1  
3              1  
4              1  
...          ...  
31487          1  
31488          1  
31489          1  
31490          1  
31491          1  

[31492 rows x 3 columns]

In [43]:
data['review']=data['review'].apply(str.lower)

In [44]:
data

review  star_rating  \
0      the motor spins and is not stationary. that se...            3   
1                                                   fake            1   
2      even though there are finally some silicone ca...            5   
3      absolutely wonderful:  this product is everyth...            5   
4      love this bluetooth speaker...easy setup, wond...            5   
...                                                  ...          ...   
31487  i bought this speaker for my wife who loves mu...            5   
31488  i bought this because i wanted to be able to b...            5   
31489  great product and really simple to install.  d...            5   
31490  this product works as advertised.  it protects...            4   
31491  received the package promptly, well packaged. ...            4   

       sentiment  
0              1  
1              0  
2              1  
3              1  
4              1  
...          ...  
31487          1  
31488          1  
31489          1  
31490          1  
31491          1  

[31492 rows x 3 columns]

In [45]:
#balancing the datasets

positive=data[data['sentiment']==1].sample(n=7425,random_state=42)

In [46]:
negative=data[data['sentiment']==0]

In [47]:
train_data=pd.concat([positive,negative]).sample(frac=1).reset_index(drop=True)

In [48]:
train_data

review  star_rating  \
0      i had first seen a vibration speaker system th...            3   
1      will not let me transfer more than about 800mb...            1   
2                              worked for maybe 2 weeks.            1   
3                                           good product            5   
4      this is my first case from maxboost and consid...            5   
...                                                  ...          ...   
14845  for the $ a great buy. my wife uses it in her ...            5   
14846  i bought the nike+ wristband for my boyfriend ...            5   
14847  very nice ipod cover. our daughter loved the c...            5   
14848  not enough shade for use in a convertible.  ma...            1   
14849  i bought this cover for my eee pc 901 20gb and...            1   

       sentiment  
0              1  
1              0  
2              0  
3              1  
4              1  
...          ...  
14845          1  
14846          1  
14847          1  
14848          0  
14849          0  

[14850 rows x 3 columns]

In [49]:
#sample reviews and labels
reviews=train_data['review'].tolist()
labels=train_data['sentiment'].tolist()

In [51]:
reviews[10:15]

["i love the stylus!  it cuts downs on errors when<br />typing or sending texts.  it's a good size and with<br />a little hook and loop on the stylus and on the ipod touch,<br />i don't lose it.",
 'many of the games are repeated over and over so there are not really 6000 different games.  also they are more for children.  where are the card games and adult interest games?',
 'everything sticks to the outside of this.  so there was nothing but hair, lint, dirt, etc stuck to this. very very disappointed!',
 'did not work with my iphone 5s',
 'this item shipped very quickly and was actually here in the first day of the range given. it was packaged in bubble wrap and is in great condition. great job! i will definately use this company again.']

In [52]:
labels[10:15]

[1, 0, 0, 0, 1]

In [53]:
#split the dataset into train,test and validation

from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test=train_test_split(reviews,labels,test_size=0.2,random_state=42)

In [57]:
len(x_train)

11880

In [58]:
len(x_test)

2970

In [60]:
#load the tokenizer
!pip install transformers
from transformers import DistilBertTokenizerFast
model_name='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer= DistilBertTokenizerFast.from_pretrained(model_name)

In [63]:
#sample tokenization
print('sentence',x_train[0])
tokenizer(x_train[0],truncation=True,padding=True,max_length=256,return_tensors="tf")

sentence we bought this item for my daughter for christmas and promptly returned it when we discovered that buying books for it was near impossible.  sony books are more than 50% more expensive and many of the books she wanted for it were unavailable    love the touch screen.  it was the reason we originally bought it.  the need to connect to computer frustrating.  it should be wireless for this price!


{'input_ids': <tf.Tensor: shape=(1, 77), dtype=int32, numpy=
array([[  101,  2057,  4149,  2023,  8875,  2005,  2026,  2684,  2005,
         4234,  1998, 13364,  2513,  2009,  2043,  2057,  3603,  2008,
         9343,  2808,  2005,  2009,  2001,  2379,  5263,  1012,  8412,
         2808,  2024,  2062,  2084,  2753,  1003,  2062,  6450,  1998,
         2116,  1997,  1996,  2808,  2016,  2359,  2005,  2009,  2020,
        20165,  2293,  1996,  3543,  3898,  1012,  2009,  2001,  1996,
         3114,  2057,  2761,  4149,  2009,  1012,  1996,  2342,  2000,
         7532,  2000,  3274, 25198,  1012,  2009,  2323,  2022,  9949,
         2005,  2023,  3976,   999,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 77), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1

#PERFORM TOKENIZATION

In [67]:
MAX_LENGTH=256
train_encodings=tokenizer(x_train,truncation=True,padding=True,max_length=256,return_tensors="tf")

In [68]:
train_encodings=tokenizer(x_test,truncation=True,padding=True,max_length=256,return_tensors="tf")