<a href="https://colab.research.google.com/github/RojaCM/NLP/blob/main/Tensorflow_tutorial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensorflow Tutorial

#### Indexing

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.random.normal([3, 3, 2])
x

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[ 0.5721696 , -0.28216806],
        [ 0.9465919 ,  1.2956209 ],
        [-0.5891881 , -0.46324497]],

       [[ 0.0779639 , -1.3711436 ],
        [-1.1159502 ,  0.8594059 ],
        [ 0.28000295, -1.3839892 ]],

       [[ 0.80899036,  0.7171591 ],
        [ 0.9812676 , -0.40212122],
        [-0.35395658,  0.23839499]]], dtype=float32)>

In [3]:
#first matrix
x[0]

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.5721696 , -0.28216806],
       [ 0.9465919 ,  1.2956209 ],
       [-0.5891881 , -0.46324497]], dtype=float32)>

In [4]:
#second matrix, third row
x[1][2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.28000295, -1.3839892 ], dtype=float32)>

In [5]:
#third matrix, first row, last element
x[2][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.7171591>

#### Slicing

In [6]:
x

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[ 0.5721696 , -0.28216806],
        [ 0.9465919 ,  1.2956209 ],
        [-0.5891881 , -0.46324497]],

       [[ 0.0779639 , -1.3711436 ],
        [-1.1159502 ,  0.8594059 ],
        [ 0.28000295, -1.3839892 ]],

       [[ 0.80899036,  0.7171591 ],
        [ 0.9812676 , -0.40212122],
        [-0.35395658,  0.23839499]]], dtype=float32)>

In [7]:
#second matrix, second row onwards
x[1][1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1159502 ,  0.8594059 ],
       [ 0.28000295, -1.3839892 ]], dtype=float32)>

In [8]:
##third matrix, first two rows
x[2][:2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.80899036,  0.7171591 ],
       [ 0.9812676 , -0.40212122]], dtype=float32)>

#### Reshaping

In [17]:
x = tf.range(96)
x

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], dtype=int32)>

In [18]:
x1 = tf.reshape(x, [2,48])
x1

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [19]:
x2 = tf.reshape(x, [2, 4, 12])
x2

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]], dtype=int32)>

In [ ]:
x3 = tf.reshape(x, [2, 4, 4, 3])
x3

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [20]:
x = tf.range(24)
x

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [21]:
x1 = tf.reshape(x, [2, -1])
x1

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]], dtype=int32)>

In [22]:
x2 = tf.reshape(x, [2, 12])
x2

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]], dtype=int32)>

In [23]:
x3 = tf.reshape(x1, [2, 3, -1])
x3

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

### Mathematical operations

In [24]:
x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [25]:
y = tf.constant(4)
y

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [26]:
x + y

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int32)>

In [27]:
x - y

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5], dtype=int32)>

In [28]:
x/y

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])>

In [29]:
tf.pow(x, 2)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [30]:
x = tf.cast(x, dtype = tf.float32)
tf.pow(x, 0.5)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [31]:
#Exponential
tf.exp(4.)

<tf.Tensor: shape=(), dtype=float32, numpy=54.59815>

In [32]:
#Logarithmic
tf.math.log(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [33]:
#matrix multiplication

a = tf.random.normal([3,2])
b = tf.random.normal([2,3])

a@b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.9584667 , -2.16746   ,  3.0826669 ],
       [ 1.0769083 ,  0.33174288, -2.7592187 ],
       [-1.0596763 ,  2.9540093 ,  1.6165957 ]], dtype=float32)>