<a href="https://colab.research.google.com/github/RojaCM/NLP/blob/main/Tensorflow_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensorflow Tutorial

### Data Types

#### 1. Scalar

##### Any Real number such as 0.4, 1.9, -0.4
##### No Dimesions, shape => []

In [ ]:
x = 8.3

import tensorflow as tf

scalar_constant = tf.constant(x)

2023-08-10 15:18:50.694588: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


VOC-NOTICE: GPU memory for this assignment is capped at 1024MiB


2023-08-10 15:18:53.717209: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [ ]:
type(x), type(scalar_constant)

(float, tensorflow.python.framework.ops.EagerTensor)

In [ ]:
scalar_constant

<tf.Tensor: shape=(), dtype=float32, numpy=8.3>

In [ ]:
#Convert this to a numpy array

scalar_constant.numpy()

8.3

#### 2. Vector

An ordered set of real numbers.

A vector tensor will have a dimension

#### 3. Matrix

A set of vectors. It will have n rows and m columns

#### 4. String

In [ ]:
a = tf.constant(['Hi How Are You?'])
a

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Hi How Are You?'], dtype=object)>

In [ ]:
tf.strings.lower(a)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'hi how are you?'], dtype=object)>

#### 5. Boolean

In [ ]:
a = tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Create a tensor

In [ ]:
tf.convert_to_tensor([3, 4.5])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3. , 4.5], dtype=float32)>

In [ ]:
tf.convert_to_tensor([1, 56])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 56], dtype=int32)>

In [ ]:
import numpy as np
tf.convert_to_tensor(np.array([[1, 1], [4,5.1]]))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 1. ],
       [4. , 5.1]])>

In [ ]:
#Zero tensor

tf.zeros((10))

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
#Ones tensor

tf.ones((10))

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
# A matrix of ones tensors

tf.ones((4,6))

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Creation from a distribution

tf.random.normal([10])

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.702883  , -0.26275355, -0.61462206, -0.644952  , -0.01354572,
        0.36128685,  1.8201486 , -0.20214039,  0.9494852 ,  1.995243  ],
      dtype=float32)>

In [ ]:
#A distribution of specific mean and stddev

tf.random.normal([10], mean=3, stddev=2)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.048321  , 3.0795329 , 6.5311613 , 0.655792  , 4.925509  ,
       2.1163082 , 5.731296  , 0.27034068, 3.4011428 , 2.1775746 ],
      dtype=float32)>

In [ ]:
#Creation from a uniform distribution

tf.random.uniform([10])

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.4193467 , 0.9849646 , 0.00145078, 0.92014873, 0.85804045,
       0.97999084, 0.2648636 , 0.98791873, 0.55106795, 0.16192496],
      dtype=float32)>

In [ ]:
#Create tensor in two dimensions from distribution

tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.10480991, -0.85618424, -1.4994951 ],
       [-1.9001081 ,  0.47008666, -1.3586289 ],
       [-0.3847567 , -1.3713881 ,  1.1280481 ]], dtype=float32)>

In [ ]:
#create a sequence of values in a tensor

tf.range(11)

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

### Basics of processing

In [ ]:
#Forward pass
x = tf.random.normal([2,4])
weight = tf.ones([4,3])
bias = tf.zeros([3])

output = x@weight + bias
output

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.2437477,  4.2437477,  4.2437477],
       [-0.556467 , -0.556467 , -0.556467 ]], dtype=float32)>

### 3 D tensor

In [ ]:
# [sequence signals, sequence length, feature legnth]

sent1 = 'I am happy'
sent2 = 'I am sad'
sent3 = 'I play cricket'

vect_sent1 = [10, 13, 40]
vect_sent1 = [10, 13, 45]
vect_sent1 = [10, 12, 23]

# 3D Tensor [no of sentences, number of words in sentence, the representation of each word]
#           [3, 3, 1]